### ISSUE TITLE
Fix parameters.yml & Environment Variables Setup & upgrade Symfony to 3.4.x

### ISSUE THREAD

**Issue by bmenant** [dis-moi/backend#151]
- [x] Symfony 3.3.x will not receive security fixes. Upgrade to 3.4.x seems reasonable.
- [x] The provisioning (from scratch) of the application from a Docker Compose environment is broken, since the `parameters.yml` does not exist (and cannot be prompted).

- [x] Then, we’ve got few warnings about deprecated environment variables uses.

- [ ] And last but not least, Clever Cloud bucket settings should not be hard-coded (plus staging and production instances should not share the same storage bucket)

- [ ] Papertail integration seemed to not work anymore.

**Comment by christpet** [comment]
I think we can either update this or close it. It still seems true that Papertrail integration doesn't work. I don't know about the Clever Cloud bucket settings... maybe @JalilArfaoui can confirm. But until then I will close it!

**Comment by JalilArfaoui** [comment]
@christpet CleverCloud settings is a thing … and not very expensive … just a config change 

Papertrail can be forgotten I think
