### ISSUE TITLE
Should licence be AGPL3?

### ISSUE THREAD

**Issue by Betree** [dis-moi/backend#223]
Hi there,

Great move publishing the code for this service, I can't wait to see it grow!

This issue is a small suggestion to move from GPL to AGPL. [This article](https://www.gnu.org/licenses/why-affero-gpl.fr.html) (in french) shortly summarizes what the difference is. The TLDR is: AGPL also forces the entity that hosts your code on their own servers to share the code if they modify it. Their may be reasons why you would prefer avoiding that, but if you want to add additional legal security to your source code it's a cheap and effective way to do it :slightly_smiling_face:

**Comment by MaartenLMEM** [comment]
Merci @Betree pour ton conseil ! On a fait le changement en ce sens.
