### ISSUE TITLE
Contributor normalizer behave differently on  staging

### ISSUE THREAD

**Issue by lutangar** [dis-moi/backend#224]
I recently added `noticesUrls` to the contributor normalizer, locally, it's rendered as an `array` as it should be, but on `staging` it's rendered as an `object` with numbered keys :/
Maybe dependencies aren't up to date on `staging`?

**Comment by JalilArfaoui** [comment]
Normally, given the `composer.lock` we should have the same dependencies installed … 

I’ll look into it …

**Comment by JalilArfaoui** [comment]
One difference between our dev stack and staging that may have an impact here : mariadb vs mysql …
