### ISSUE TITLE
When a user creates a contribution with DisMoi Add-on, it creates a private bubble in Backoffice.

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/backend#302]
NB : de mémoire cette fonctionnalité avait été commencée par @JalilArfaoui 

Actuellement, lorsqu'un utilisateur crée une bulle depuis l'extension, un mail est généré et traité par l'équipe éditoriale via des copiés collés.

La  présente évolution vise à ce que la contribution soit directement pré-intégrée dans le BO.
L'alerte mail demeure ne fonctionnalité existante afin de prévenir l'équipe éditoriale d'une contribution à traiter.

**Comment by JalilArfaoui** [comment]
Ça avait été commencé dans #161

**Comment by MaartenLMEM** [comment]
testé ! du travail de pro !
