### ISSUE TITLE
[staging BO] Error 500 when creating a new admin user

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/backend#311]
![image](https://user-images.githubusercontent.com/7824485/109666488-85b8d000-7b6f-11eb-9638-b9111f2ee571.png)

**Comment by MaartenLMEM** [comment]
Hum : it seems I created a user with a username that already existed. 
I think we can close this issue until it appears again.

**Comment by MaartenLMEM** [comment]
I just tried to create a new contributor (not existing) all right it works.

**Comment by christpet** [comment]
Ah! Okay, great news. Thanks for re-testing. I will close it for now. To note for the next contributor interface to put in some validation for this.
