### ISSUE TITLE
Automatic contributions for CaptainFact fact-checking

### ISSUE THREAD

**Issue by julienadamcom** [dis-moi/backend#325]
Connection to the CaptainFact's GraphQL API to sync their DisMoi contributions and the youtube videos they analyse.

Usage: when a DisMoi user watches a video on youtube, if he follows the CaptainFact contributor and if the video has been analysed by the CaptainFact community, a bubble appears and allows to read the results of this analysis.

**Comment by christpet** [comment]
Thanks for submitting @julienadamcom ! Looks great. Could you add a little more info about why this is high priority? Would this cause a lot more users to start using Dismoi, or improve retention a lot? 

I want to make sure we're building things that help us reach those top-level goals, and not *just* because a partner asked for it.

Also, could you add an estimate of what size project this is? XS - S - M - L - XL (you can put this in a label)

Just FYI, I'm moving this to the "In Progress" column on the Backend project board since it looks like you've started on it already.

**Comment by MaartenLMEM** [comment]
To help here, here are some criteria we use to assess contributions value that seem to me suitable to this kind of contribution features : 
In order :
**1. Covering** more web experiences. It depend of audience, on a year. 
**2. Relevance** : it matches pages that are really about the same matter
**3. Bring usefull and interesting information** : people spend time to read it, they appreciate it
**4. Gather an exisiting community**, large and binded (whose members are close one to each other)
**5. Attractive for media or social media** acquisition 

If we apply those criteria here :
**1. Coverage** : We ll probably cover very poupular vidéos, but only after first hours when there are the most views, beacause of delay of factchecking form CaptainFact community.
Videos audience decreases very fast after first days, but there are still people watching it next months.
For same videos that are **not** hosted on Youtube, we all have to add manually matchinf context . But most is happening on Youtube, so it 's not a little limit.
**2. Relevance ** : Perfect
**3. User interest** : I don"t have information about it. For members of CaptainFact of course. For others, I can imagine, but hard to be affirmative here.
**4. Community** : +++
**5. Attractive for media** : +++

**Comment by christpet** [comment]
OK seems like a clear go from the prioritization perspective, thank you @MaartenLMEM for the context!

**Comment by MaartenLMEM** [comment]
hello @julienadamcom un point dont on n'a pas discuté c'est la recette de cette automatisation CaptainFact.
Si j'ai bien compris c'est déjà en prod avec la prise en compte des matching context existants.
Est-ce que du coup Camille peut recetter ?

**Comment by julienadamcom** [comment]
Hello @MaartenLMEM, je n'ai pas répondu tout de suite parce que j'ai dû adapter le regex ce weekend, mais tout est prêt maintenant et le contributeur CaptainFact a désormais ses 353 contributions et en effet Camille peut vérifier tout ça !

Reste à automatiser la synchro toutes les nuits, je programmerai ça pour la prochaine MEP

**Comment by MaartenLMEM** [comment]
@CamilleRolland pour recette stp (à ta dispo si tu as des questions)
