### ISSUE TITLE
Implement an authentication API endpoint for users

### ISSUE THREAD

**Issue by lutangar** [dis-moi/backend#332]
> Following discussion in #324

## Step 0

Allow users to login via an API.

## Step 1

> In order to allow a `Contributor` to post a `Notice` via an API (see issue #333) 
> The `Contributor` must be able to authenticate.

### Mission
Update current model to allow this new feature and implement a new kind of user if necessary.

> Might need to create a user linked 1to1 to a contributor.

To see what's expected in the future for user roles and ACLs see this previsionnal table:
  | ASKER | USER | LITE | PRO | ADMINPRO | ADMIN
-- | -- | -- | -- | -- | -- | --
ask question |   |   |   |   |   |  
extension - view |   | ✅ | ✅ | ✅ | V2 | ✅
extension - post |   |   | ✅ | ✅ | V2 | ✅
BO - post |   |   | ✅ | ✅ | V2 | ✅
posting rights |   |   | own channel | own channel | own channel(s) | all
posting location |   |   | Interface contributeur | Interface contributeur | V2 | existing BO

> https://docs.google.com/document/d/1B-Uu4LYXKa8-q3JPhuVXvg0wgJlJIHEfuAkGPUPsRss/edit#heading=h.j8slwrs1cjsc

> For earlier version/work on implementing a user/contributor, might be outdated tho'
> #12

## Step 2
 
 (see issue #333)

**Comment by MaartenLMEM** [comment]
Important point @Goutte : User has an email and a password. He do not have a name.
Only contributors have a name.
It is important because, for a user, handling two names would be awkward.

**Comment by prk-dismoi** [comment]
Hi @Goutte/@lutangar what is the latest on this one?
