### ISSUE TITLE
Create sources & contributions in English (English Version)

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/backend#343]
Target : US websites 
Id there is a direct link to an alternative, Us website also, of course. 

**Source 1 : TheWirecutter - 3 bubbles with scrrenshot 
Name of contributor : TheWirecutter fan ?

**Comment by MaartenLMEM** [comment]
@zhinu Do you have already have some interesting American or English sources to automate ? (I moved this question from another card)

**Comment by zhinu** [comment]
> @zhinu Do you have already have some interesting American or English sources to automate ? (I moved this question from another card)

I am thinking about it. But the video games automation will work for en-US, as well as the first batch of scamblocker list.

**Comment by lutangar** [comment]
Before adding any en-* contributor/notice we should, at least, add a simple discriminant to the model.
It could be a simple `lang` flag added to a `Contributor` AND/OR to a `Notice`.

Will then be able to propose a list of `Contributor` for given `lang` AND/OR a list of `Notice` for a given `lang`.
Are we going to create specific `Contributor` for given `lang` or shall a `Contributor` be able to post `Notice` in any `lang`?

**Comment by MaartenLMEM** [comment]
@lutangar  Your remarks look good for this feature we plan to tackle after : https://github.com/dis-moi/extension/issues/794 Isn't it ? 
Just a quetion : why before dev before content ?

**Comment by lutangar** [comment]
Because adding the discriminant afterward would involve changing the `Notice` and `Contribution` language manually.

**Comment by JalilArfaoui** [comment]
I understand adding a `locale` field to a `Contributor` (or `locales` ?)

But it feels awkward on `Notice`s … Are we going to expect from a contributor posting from the extension that he specifies the language he/she’s using ?

**Comment by J-oh-n** [comment]
3 suggestions of US-EN guides :
- [consumer] [Wirecutter](https://www.nytimes.com/wirecutter/) (NY Times)
- [fact-checking] [Washington Post Fact Checker](https://www.washingtonpost.com/news/fact-checker/), otherwise [FactCheck.org](https://www.factcheck.org/)
- [entertainment] [IMDB rating](https://www.imdb.com/) (property of Amazon)
ps : Oprah Winfrey crossed my mind but not much value

**Comment by MaartenLMEM** [comment]
https://trello.com/c/f4VVO60I

**Comment by lutangar** [comment]
> I understand adding a locale field to a Contributor (or locales ?)
> But it feels awkward on Notices … Are we going to expect from a contributor posting from the extension that he specifies the language he/she’s using ?

@MaartenLMEM I think we still need your input on this.

**Comment by MaartenLMEM** [comment]
> > I understand adding a locale field to a Contributor (or locales ?)
> > But it feels awkward on Notices … Are we going to expect from a contributor posting from the extension that he specifies the language he/she’s using ?

Main language is only a contributor property, in order to display him before other contributoprs to users spaking same language.
Currenlty, we do no need a language property on notices.

**Comment by MaartenLMEM** [comment]
Please take this comment in account for https://github.com/dis-moi/extension/issues/795

**Comment by MaartenLMEM** [comment]
Content are online and validated.

**Comment by lutangar** [comment]
> Please take this comment in account for dis-moi/extension#795
Which comment?

> Contents are online and validated.
What content are you talking about? Could you link them?

**Comment by MaartenLMEM** [comment]
> 
> 
> > Please take this comment in account for dis-moi/extension#795
> 
> Which comment?

Sorry was a mistake.

> > Contents are online and validated.
> 
> What content are you talking about? Could you link them?
Based on https://trello.com/c/f4VVO60I ... but I see John asked some refinement, but doesn't matter, from our point of view it s done.
Current card is only about contents : creating profiles and their contributions.

**Comment by gregoirelacoste** [comment]
> I understand adding a locale field to a Contributor (or locales ?)
> But it feels awkward on `Notice`s … Are we going to expect from a contributor posting from the extension that he specifies the language he/she’s using ?

If only the language of a contributor is specified, nothing will tell that a notice is effectively in the contributor language and not in another language.
Indeed, it may be possible that a contributor wants to translate his notice into several languages to maximize his visibility for example.

Wouldn't it be interesting to put the local property to both?
By always taking the contributor's language by default on the notices but leaving the possibility of changing the language by notice?

In this way one would display in front only the contributions of the language of the user and not the contributions written by a contributor of the language of the user

**Comment by JalilArfaoui** [comment]
I have mixed feelings about that. 
- In one hand, I see that Twitter for instance does not allow a user to specify in what language is written a particular tweet. 
- In the other and, I see users struggling with this fact, either creating one account per language or having a unique account with duplicated tweets when they want to localize their messages … And I realize that it would be a nice feature to be able, optionally, to specify the language of a tweet, but even better, to be able to write a single tweet in multiple languages.

So I’m wondering if we shouldn’t have : a `Notice` that holds the general infos and matching contexts, and associated to that notice one field per language we want ! Of course, by default, only one field is initialized, in the default language of the user …

**Comment by MaartenLMEM** [comment]
>     * In one hand, I see that Twitter for instance does not allow a user to specify in what language is written a particular tweet.
Yes it s automated in their algorithm. We are at the first stage, so we do it manually, one by one.

>     * In the other and, I see users struggling with this fact, either creating one account per language or having a unique account with duplicated tweets when they want to localize their messages … And I realize that it would be a nice feature to be able, optionally, to specify the language of a tweet, but even better, to be able to write a single tweet in multiple languages.

This is an advanced usage. hope we ll have this kind of problem soon ^^

> So I’m wondering if we shouldn’t have : a `Notice` that holds the general infos and matching contexts, and associated to that notice one field per language we want ! Of course, by default, only one field is initialized, in the default language of the user …

Yes this field is planned.

**Comment by MaartenLMEM** [comment]
all thoses comments apply to https://github.com/dis-moi/extension/issues/795
Current card is done.
