### ISSUE TITLE
Software and process to handle BO data

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/backend#344]

**Comment by zhinu** [comment]
#### to do

Replace WPS with python script to automatically analyze csv (panda & ipython : https://softwarerecs.stackexchange.com/questions/21628/linux-alternative-to-excel-pivot-table )

**Comment by zhinu** [comment]
Issue not relevant anymore with the google data studio/metabase dashboard.
linked with [https://github.com/dis-moi/backend/issues/361](https://github.com/dis-moi/backend/issues/361)
