### ISSUE TITLE
When creating a notice with a long Xpath - error 500

### ISSUE THREAD

**Issue by zhinu** [dis-moi/backend#349]
So when trying to input the following xpath (for the guerilla marketing):
> //*[@data-qa-id='adview_description_container']//text()[(contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'mandat postal') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'mandat cash') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'western union')) and not(contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'pas de mandat postal') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'mandat postal refusé') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'mandat cash refusé') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'western union refusé') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'pas de mandat cash') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'pas de western union') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'aucune demande de location avec acompte par mandat postal ou western Union') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'Refuse les paiements par western union') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'Pas de Reglement via Western Union') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'Pas de réservation par mandat') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'Les pionniers de la Western Union'))]

This error occurs:
![image](https://user-images.githubusercontent.com/75084558/115031450-75af4280-9ec8-11eb-8f59-dcb64b7d1fd1.png)

I needed to modify the notice #1869

**Comment by lutangar** [comment]
@zhinu could you put together an example on `staging` env plz?
- Link to the backend notice
- Link to an example URL

Does it works when only looking for one sentence?

**Comment by zhinu** [comment]
[notice #1259](https://staging-notices.lmem.net/admin/?action=edit&entity=Notice&sortField=id&sortDirection=DESC&page=1&referer=%252Fadmin%252F%253Faction%253Dlist%2526entity%253DNotice%2526sortField%253Did%2526sortDirection%253DDESC%2526page%253D1&id=1260)

it works with a simple xpath 
> //*[@data-qa-id='adview_description_container']//*[contains(text(),'paypal')]

But same error with the longer one

**Comment by zhinu** [comment]
The server doesn't seem to accept complicated xpath

**Comment by zhinu** [comment]
[https://www.darty.com/nav/extra/offres?codic=4738454#state_1](https://www.darty.com/nav/extra/offres?codic=4738454#state_1)

**Comment by lutangar** [comment]
Alright got it, field is too small:
```
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'xpath' at row 1
```
Max length is currently `255` we must migrate this field.

**Comment by MaartenLMEM** [comment]
@zhinu Can you confirm it is working well now ?

**Comment by zhinu** [comment]
Yes all good now :)
