### ISSUE TITLE
When I want to add a contributor a 500 error appear after submit

### ISSUE THREAD

**Issue by felix-lambert** [dis-moi/backend#351]
I've entered all the fields except "Bulles phares". I've added some images

It's in https://notices.lmem.net as admin

**Comment by lutangar** [comment]
Looks like #304 but it was supposed to be fixed. Could you have a look at this @Goutte ?

**Comment by Goutte** [comment]
Sure can !   Give me an error trace here or access to the https://notices.lmem.net in MP !

**Comment by MaartenLMEM** [comment]
@Goutte I create an access and sent it to you by MP.
