### ISSUE TITLE
Make the advanced contribution tool close source

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/backend#369]
First step : sizing 
@gregoirelacoste could make a first guess and then Jalil and Johan will review
Please list tasks involved to make this change and to work well with this separate repo next months.

**Comment by gregoirelacoste** [comment]
@JalilArfaoui @lutangar to know the implication of this task, we must first validate the stack.
I would go on the same as profile (react, redux ...).
However, we could also consider php, as is the case today for the contribution interface?

**Comment by lutangar** [comment]
I changed the title, because it wasn't clear enough. We'll discuss the implications in this afternoon meeting.
As for the stack this will be a PWA made with React, others libs choices may be subject to changes depending on the strategy.

Making this tool private would require the following:

Pros:
- New stack without previous technical debt?
- ???

> I'm not the right person to defend the pros here, business team is the one that should do it.

Cons:
- New stack to setup (time)
- we can't reuse logic previously written in extension and profiles
- we need to publish the `components` lib (often wrongly called  "the storybook") and thus create the CI associated with this process
- Specific development process when working on the contribution interface (linking local `components` lib to work on both at the same time)

**Comment by gregoirelacoste** [comment]
if thanks to NX we can have multiple public repositories and a private repository, it might solve time and shared component issues:
maybe an answer: https://github.com/nrwl/nx/issues/1235

**Comment by JalilArfaoui** [comment]
> The line between free contributor and paid contributor will very likely be the number of bubbles seen or the number of followers.

I don’t get it.

> leaving the code open-source for those features might endanger the business model and the sustainability of the projet.

We can always let our client (here, the advanced contribution interface) open source and have a feature control at the backend-level. Meaning that if a user wants to use a paid feature, we can allow/reject the request at the backend side, depending on his/her/its subscription. 

And even inside the advanced contribution interface, we might want to differentiate between a couple of pricing levels, so availability of the source code is not the best mechanism. Also, a paid account can be cancelled, etc…

With a backend level subscription control, we don’t care that a user have the source code of the interface : If the user account is not authorized for the feature he/she’s trying to use, it won’t work.

> another organization copies all DisMoi source code, creates a new platform, and makes all features free for everyone.

As with all (centralized) networks, our strength is and will be our data and existing usage (contributors, contributions, installed extensions). I’m not sure that it’s likely that someone who just copy our platform will be able to make all our user base switch to it. And if it is likely, then having just the contribution interface closed-source appears to be an insufficient protection IMHO. Someone this close to take on us will always be able to develop its own client (interface).

**Comment by gregoirelacoste** [comment]
Isn't there also the desire to offer a single tool to centralize contributors within a single space and thus speak more simply to them?

**Comment by newick** [comment]
> Isn't there also the desire to offer a single tool to centralize contributors within a single space and thus speak more simply to them?

in a near future, the Users could contribute form this UI and the extension, and if I got it correctly, from the mobile app. 

IMO if a better interface exists and can be plugged to our backend, it's a win, it means people want to contribute. 
And if I get correctly @JalilArfaoui's point, we could limit it depending the kind of account.

**Comment by MaartenLMEM** [comment]
Following meeting about this subject leaded by John,  this is issue is closed.
