### ISSUE TITLE
Contributor intro is limited to 255 characters

### ISSUE THREAD

**Issue by zhinu** [dis-moi/backend#393]
![image](https://user-images.githubusercontent.com/75084558/121817948-a6231b00-cc84-11eb-9940-4f3f9ea2bb9c.png)

Negative side effect :
- Some intros need more than 255 characters
- Including any type of svg path or other small visual code won't work.

**Comment by zhinu** [comment]
![image](https://user-images.githubusercontent.com/75084558/121819042-57c54a80-cc8b-11eb-803d-ed6dcfc90345.png)
The db structure in itself doesn't allow for more than 255 chars

**Comment by MaartenLMEM** [comment]
@gregoirelacoste I pass the task to you.
- On contributor side in BO, I do not see any restriction. 
- On internet user side, profiles texts are used on profile page only.
Please see directly this matter with @zhinu .
