### ISSUE TITLE
BO : interdire l'étoile seule dans le champ Regex

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/backend#401]
Lorsque l'utilisateur met juste une étoile dans le champ regex : 
- le champ devient rouge (comme lorsque la regex ne matche pas avec l'url exemple)
- optionnel : le contributeur ne peut pas enregistrer sa bulle (_Ne faire cette partie que c'est rudimentaire et sans risque d'effet secondaire_)

**Comment by zhinu** [comment]
see #405
