### ISSUE TITLE
Avoid bulles.fr domain for our own services - before july 21th

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/backend#417]
On utilise encore  bulles.fr encore en url de certains de nos services internes.
Ce serait bien de s'en passer. Dans 3 jours le domaine est expiré donc à faire mercredi au plus tard.
https://admin.gandi.net/domain/9fa864cc-51b0-11e7-88f3-00163ec31f40/bulles.fr/overview

**Comment by MaartenLMEM** [comment]
@lutangar je renouvelle le domaine par précaution tant que cette issue n'est pas réalisée

**Comment by lutangar** [comment]
Yes do that, I had an eye on this but we won't be ready by the end of today anyway... (time to release to Chrome prod the extension)
