### ISSUE TITLE
https://www.trivago.fr/fr/srl?__wr=2&search=100-341576 does not show any notice

### ISSUE THREAD

**Issue by felix-lambert** [dis-moi/backend#430]
You can go to this url by clicking on Voir un example réel of FairBooking with firefox. 

regex list and comparaison:

///////////////////////////////////////////////////////
trivago.fr/fr/srl?__wr=2&search=100-341576
{"id": 471, "noticeId": 116, "noticeUrl": "https://notices.bulles.fr/api/v3/notices/116", "urlRegex": "(trivago\\.fr).*adagio"}
 ////////////////////////////////////////////////////////
//////////////////////////////////////////////////////
trivago.fr/fr/srl?__wr=2&search=100-341576
{"id": 1312, "noticeId": 275, "noticeUrl": "https://notices.bulles.fr/api/v3/notices/275", "urlRegex": "(trivago\\.fr).*mas.*de.*oulivie"}
 ////////////////////////////////////////////////////////
 ///////////////////////////////////////////////////////
trivago.fr/fr/srl?__wr=2&search=100-341576
 {"id": 1415, "noticeId": 301, "noticeUrl": "https://notices.bulles.fr/api/v3/notices/301", "urlRegex": "(trivago\\.fr).*abbaye.*talloires"}
 ////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////
trivago.fr/fr/srl?__wr=2&search=100-341576
 {"id": 1418, "noticeId": 302, "noticeUrl": "https://notices.bulles.fr/api/v3/notices/302", "urlRegex": "(trivago\\.fr).*hotel.*de.*harlay"}
 ////////////////////////////////////////////////////////
 ///////////////////////////////////////////////////////
trivago.fr/fr/srl?__wr=2&search=100-341576
{"id": 50, "noticeId": 27, "noticeUrl": "https://notices.bulles.fr/api/v3/notices/27", "urlRegex": "(www\\.trivago\\.fr).*(sofitel|pullman|mgalerry|mercure|sebbel|novotel|shelter)"}
////////////////////////////////////////////////////////
///////////////////////////////////////////////////////
trivago.fr/fr/srl?__wr=2&search=100-341576
{"id": 466, "noticeId": 115, "noticeUrl": "https://notices.bulles.fr/api/v3/notices/115", "urlRegex": "(www\\.trivago\\.fr)/.*ibis"}
////////////////////////////////////////////////////////
///////////////////////////////////////////////////////
trivago.fr/fr/srl?__wr=2&search=100-341576
{"id": 3883, "noticeId": 1347, "noticeUrl": "https://notices.bulles.fr/api/v3/notices/1347", "urlRegex": "(fr\\.hotels\\.com|hotels\\.com|www\\.booking\\.com|www\\.ebookers\\.fr|www\\.expedia\\.fr|www\\.trivago\\.fr).*hotel"}
////////////////////////////////////////////////////////
///////////////////////////////////////////////////////
trivago.fr/fr/srl?__wr=2&search=100-341576
{"id": 3849, "noticeId": 1321, "noticeUrl": "https://notices.bulles.fr/api/v3/notices/1321", "urlRegex": "(fr\\.hotels\\.com|hotels\\.com|www\\.booking\\.com|www\\.ebookers\\.fr|www\\.expedia\\.fr|www\\.trivago\\.fr)(/?(\\?.*)?$|/index.fr.html)"}
////////////////////////////////////////////////////////

As a comparaison I do this: 

`if (www.trivago.fr/fr/srl?__wr=2&search=100-341576.match(new RegExp(matchingContext.urlRegex, 'g')`

And it's always false on mobile side

**Comment by JalilArfaoui** [comment]
Currently, the pinned notice for `FairBooking` contributor is notice id 275 … this notice’s first matching context example URL is https://www.trivago.fr/les-baux-de-provence-87963/hotel/mas-de-l-oulivie-hotel-341576

It’s working well with matching context regex `trivago.fr/.*mas.*de.*oulivie` …

I can’t see why www.trivago.fr/fr/srl?__wr=2&search=100-341576 should match … but maybe production data changed since this summer …

I’m closing this, feel free to reopen if problem is still current.
