### ISSUE TITLE
When I create a protodomain with a domain already existing, I am blocked for duplicate reason

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/backend#432]
I wanted to create a protodomaine : www.zalando.fr/sneakers
but since www.zalando.fr already exists, Easyadmin blocks me.

![image](https://user-images.githubusercontent.com/7824485/128012250-23276762-80a4-47bf-9593-ce52d44fd5b1.png)

---
**Note for myself after this issue is solved :** 
Add www.google.fr/maps as protodomain and modify bubbles related such as #1937

**Comment by MaartenLMEM** [comment]
@lutangar on est bloqué par cette issue que j'avais un peu oublié. Je l'ai mise à colonne "this week" dans la mesure du possible.

**Comment by lutangar** [comment]
After some testing some more work were required (see #443

**Comment by MaartenLMEM** [comment]
all right @lutangar
Please put it into production.

**Comment by MaartenLMEM** [comment]
tested, all right !
