### ISSUE TITLE
BO is slow since a couple of days

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/backend#439]
Lors de la création et la mise à jour des bulles, il y a plusieurs seoncdes chargement et parfois des lags lors de la saisie.

**Comment by zhinu** [comment]
J'ai un temps de chargement très lent (1/2 minute parfois), et ça finit souvent en page blanche...

**Comment by MaartenLMEM** [comment]
@lutangar j'ai l'impression que ça s'aggrave, je te l'attribue pour cette semaine. On en reparle demain en réu.

**Comment by lutangar** [comment]
> see #440 resolution
