### ISSUE TITLE
All services linked to BO are down or very slow, with 504 erros sometimes

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/backend#440]
Situation got worse every day, but today it s a more significant :
- Profile pages are down on prod and proding/staging
- We cannot work in the BO. We are blocked

Related to https://github.com/dis-moi/backend/issues/439

**Comment by MaartenLMEM** [comment]
@lutangar @JalilArfaoui What about cleaning whole cache on Cloudflare ?

**Comment by lutangar** [comment]
Probably would be worse...

**Comment by lutangar** [comment]
Fixed via new CloudFlare config on new API domain.
