### ISSUE TITLE
Local tag for contributors, managed in BO

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/backend#458]
## Stages
- [ ] Create tag in BO
- [ ] Expose it on the API

## Stakes 
- Filter local profiles for LMEL Android app and for LMEL web extension

## Reorder current categories ? 
We already have some categories used to filter profiles list : Conso, Culture et Société, Militant, Divers

A local category could be added here. 
But look out here : We cannot just add or replace a category. We have to redesign the whole. 
A first draft I made to deal with in depth : Conso - Conso locale - Factcheck - Citoyens & experts

**Comment by prk-dismoi** [comment]
"Conso locale" is the urgency here, as a prerequisite flag for filtering contributors on LMEL (the app has "local" and "autres" tab). We need to think whether categories will be mutually exclusive or not (i.e. is conso locale a subset of conso?). If not we could just add a DB flag on contributors for now (for ex: local Y/N). This way we also don't have to agree on how to rename the categories just yet.

**Comment by MaartenLMEM** [comment]
- Good point : `Local `is a subset of `Conso`. It is the most logical, closest to reality.
- We will see how to manage this category on apps and browser add-on after. for this last one cf. https://github.com/dis-moi/extension/issues/1151
- Yet, the main criteria here is the ease to develop.

**Comment by MaartenLMEM** [comment]
About redesign categories. Actually, I think it is not mandatory. 
Yet, if we would like to improve these categories, it will need a little design work. Involving such methods https://www.nngroup.com/articles/card-sorting-definition/

**Comment by JalilArfaoui** [comment]
@prk-dismoi @MaartenLMEM I’m not sure what we stated here … 

Is it OK for now to just add a `local contributor` checkbox to the contributor ? Or are we redesigning the whole category system ?

**Comment by MaartenLMEM** [comment]
> @prk-dismoi @MaartenLMEM I’m not sure what we stated here …
> 
> Is it OK for now to just add a `local contributor` checkbox to the contributor ? Or are we redesigning the whole category system ?

@JalilArfaoui This seems me the easiest way yes.

**Comment by JalilArfaoui** [comment]
@MaartenLMEM I close this, as :
 - We don’t need this anymore for https://github.com/dis-moi/extension/issues/1151
 - We may re-think the whole category functionality later
